services:
  backend:
    image: 035863456454.dkr.ecr.us-east-1.amazonaws.com/bookstore-backend:latest
    ports:
      - "8800:8800"
    environment:
      RDS_HOST: ${RDS_HOST}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      DB_NAME: ${DB_NAME}
      # DB_PORT: 3306

  frontend:
    image: 035863456454.dkr.ecr.us-east-1.amazonaws.com/bookstore-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend