services:
  backend:
    build:
      context: ../source-repo/backend
    ports:
      - "8800:8800"
    environment:
      RDS_HOST: ${RDS_HOST}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend:
    build:
      context: ../source-repo/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend