name: Deploy Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4
        with:
          repository: aawihardja-usfca/bookstore

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BACKEND_REPOSITORY: bookstore-backend
          FRONTEND_REPOSITORY: bookstore-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPOSITORY:latest ./backend
          docker build -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest ./frontend

      - name: Run tests
        # no test cases was provided
        run : |
          docker compose up -d
          docker compose down

      - name: Push Docker images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BACKEND_REPOSITORY: bookstore-backend
          FRONTEND_REPOSITORY: bookstore-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:latest
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:latest

