name: Deploy Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4
        with:
          repository: aawihardja-usfca/bookstore
        
      - name: build Docker images
        run : |
          docker build -t backend ./backend
          docker build -t frontend ./frontend
      
      - name: run tests
        # no test cases was provided
        run : |
          docker compose up -d
          docker compose down

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: verify AWS credentials
        run: aws sts get-caller-identity
      
